# Generated by Django 2.2 on 2019-04-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0003_unique_species_constraints_tuple'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specimen',
            name='nickname',
        ),
        migrations.AddField(
            model_name='specimen',
            name='happened_at',
            field=models.DateField(null=True),
        ),
    ]
