# Generated by Django 2.2 on 2019-05-08 10:20

import core.models.photo
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0004_specimen_refactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='title',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='organism',
            name='name',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='photo',
            name='path',
            field=models.ImageField(upload_to=core.models.photo.Photo._upload_to_path),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='taxonomicspecies',
            name='name',
            field=models.CharField(db_index=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='taxonomicsubspecies',
            name='name',
            field=models.CharField(db_index=True, max_length=45),
        ),
    ]
